name: CI

on:
  push:
    branches:
      - main
      - 'feature/*'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10.10]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Cache NLTK data
      uses: actions/cache@v2
      with:
        path: ~/.cache/nltk
        key: ${{ runner.os }}-nltk-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-nltk-

    - name: Cache SpaCy data
      uses: actions/cache@v2
      with:
        path: ~/.cache/spacy
        key: ${{ runner.os }}-spacy-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-spacy-

    - name: Cache GloVe data
      uses: actions/cache@v2
      with:
        path: ~/.cache/gensim-data
        key: ${{ runner.os }}-glove-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-glove-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install SpaCy model
      run: |
        python -m spacy download en_core_web_sm

    - name: Install NLTK data
      run: |
        python -m nltk.downloader punkt
        python -m nltk.downloader wordnet

    - name: Download GloVe model
      run: |
        python -c "import gensim.downloader as api; api.load('glove-wiki-gigaword-50')"

    - name: Run tests with coverage
      run: |
        coverage run -m unittest discover -s tests
        coverage xml
        coverage html

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: htmlcov

    - name: Upload coverage XML
      uses: actions/upload-artifact@v3
      with:
        name: coverage-xml
        path: coverage.xml

    - name: Publish coverage to Coveralls
      if: ${{ github.event_name == 'push' }}
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}